### PR TITLE
Use seam-connect-fake for local development

### PR DESCRIPTION
**Pull request by razor-x**
- Runs and uses the [fake-seam-connect](https://github.com/seamapi/fake-seam-connect) for the local storybook.
- Uses fake for Jest (almost working, try here for exit code fix https://github.com/open-cli-tools/concurrently/issues/187#issuecomment-1274659502)

### CODE REVIEW

**Comment by razor-x** [comment]
Needs https://github.com/seamapi/fake-seam-connect/pull/3 and the new version from that for the port option to work.

**Comment by razor-x** [comment]
Note that I really tried to get jest to start and stop the fake, but all efforts failed so I fellback to using concurrently.

**Comment by razor-x** [comment]
@seveibar This is working with Jest now. We shouldn't merge this though until the fake is updated with more endpoints.

**Comment by seveibar** [comment]
@razor-x yep! Hopefully i will have a good batch of endpoints tonight!!!

**Review by seveibar — APPROVED** [review]

**Comment by razor-x** [comment]
Closing in favor of https://github.com/seamapi/react/pull/75

**Pull request closed without merging**
