### PR TITLE
fix: avoid style injection

### PR DESCRIPTION
**Pull request by mikewuu**
An alternative approach to the one taken in https://github.com/seamapi/react/pull/182, which offers automatic style loading without versioning, or style injections:

- Includes styles by default.
- Always import `index.css` in `<SeamProvider/>`.
- Allows the user to opt-out by specifying `disableStyles`.

CleanShot 2023-05-28 at 17 02 43

### CODE REVIEW

**Comment by razor-x** [comment]
I'd like to avoid this approach as it requires a bundler that understands how to bundle css. As-is, the lib compiles with TSC to a standard es module which is very compatible. I am looking at turning these into web components and I think this change will further complicate that.

**Comment by mikewuu** [comment]
Fair enough. Still wrapping my head around the fact that this is a lib, and we don't have a bundler.

**Comment by razor-x** [comment]
No worries. Even if we used a bundler that could import css, then you have to ask: what would it replace the import with at bundle time? It would have to either be inline styles or a link to a cdn hosted stylesheet 😁

**Comment by mikewuu** [comment]
Don't bundlers just combine all css imports into a single index.css file?

To your point, guess we can't assume that.

**Comment by razor-x** [comment]
> Don't bundlers just combine all css imports into a single index.css file?

That is exactly what Sass cli is doing right now.

**Pull request closed without merging**
