### PR TITLE
`seam-table` refactor

### PR DESCRIPTION
**Pull request by Andrewjeska**
https://github.com/seamapi/react/pull/348#discussion_r1294071182

We needed some more general table classes

### CODE REVIEW

**Comment by razor-x** [comment]
@mikewuu may want to take a look.

**Review by razor-x — CHANGES_REQUESTED** [review]
Something is up with the UI Tests. Let's try to resolve before merging. The updates may have broken the layout.

**Review by mikewuu — APPROVED** [review]

**Comment by Andrewjeska** [comment]
> Something is up with the UI Tests. Let's try to resolve before merging. The updates may have broken the layout.

`seam-access-code-details` and `seam-code-details` are very different things. 

I think using `seam-details` vs `seam-code-details` is slightly better, but I wish it was more specific. `seam-table-row-details` ? 

[523e289](https://github.com/seamapi/react/pull/350/commits/523e28950ebb2b60605945bb2ddafe2ec0f488eb)

**Review by razor-x — APPROVED** [review]
All hail Cromatic 🌈

**Pull request merged**
