### PR TITLE
feat: Add disableDeviceManufacturerInformation prop

### PR DESCRIPTION
**Pull request by razor-x**
- **feat: Add disableDeviceManufacturerInformation prop**
- **Hide DeviceInfo if all sections are disabled**

### CODE REVIEW

**Review by mikewuu — APPROVED** [review]

**Review by xplato — APPROVED** [review]

**Comment by dawnho** [comment]
Could you add screenshots that illustrate what the prop changes?

**Comment by dawnho** [comment]
I don't think we need to get so granular with these flags. i wanted the whole device info / details section to get hidden, instead of these granular row by row flags.

**Comment by razor-x** [comment]
> Could you add screenshots that illustrate what the prop changes?

@dawnho The storybook for this branch will let you see all the different component states: https://react-hsmbsz7gy.seam.vc/?path=/docs/components-devicedetails--docs

**Review by dawnho — APPROVED** [review]
Btw, the API Docs are a bit out of date. I'd love to figure out a way to easily surface the props / css classes there.

The nice thing about doing things via props is, storybook actually has an addon for converting the props into documentation:
https://storybook.js.org/addons/@storybook/addon-docs

Just a thought!

**Pull request closed without merging**
