### PR TITLE
feat(AccessCodeForm): invert set time zone manually checkbox

### PR DESCRIPTION
**Pull request by mikewuu**
Requested via [Slack]( https://hello-seam.slack.com/archives/C051ETBPRTQ/p1689874525095959?thread_ts=1689808685.428099&cid=C051ETBPRTQ)

https://github.com/seamapi/react/assets/11449462/0c3c7a1a-a515-4f83-8610-11f2cfe6ebf1

### CODE REVIEW

**Comment by razor-x** [comment]
Can you make it so when we click on the select box, if the box is not checked, it checks the box and opens the selection up?

**Comment by mikewuu** [comment]
I think so, but it might be better to have user take explicit action (toggling) box instead so that they're aware of the switch from manual/auto. wdyt?

**Comment by razor-x** [comment]
IMO this is already better. Personally I want to click the box right away and not be slowed down by an extra click, but I can be convinced the extra click is needed.

CC @miken-seam

**Review by razor-x — APPROVED** [review]
I like it. Let's hold off merging until we get some more feedback in the comments.

**Review by dawnho — APPROVED** [review]
I agree with @razor-x 's suggestion about opening up the list when the checkbox is unchecked

**Pull request merged**
